Fixed compatibility issue.
On pip install django-currentuser we get this stacktrace:

ERROR: django-currentuser 0.4.1 has requirement Django<2.0,>=1.11.17,
but you'll have django 2.2.2 which is
incompatible.
ERROR: django-currentuser 0.4.1 has requirement Django<2.2,>=2.1.8;
python_version > "3.4", but you'll have
django 2.2.2 which is incompatible.

Also the TravisCI builds were failing.